### PR TITLE
add hyperspec.utils

### PR DESCRIPTION
**Pull request by konradmayer**
Dear Bryan Hanson, thanks for this awesome resource!
I wrote a small utility package {[hyperspec.utils](https://konradmayer.github.io/hyperSpec.utils/)} to work with objects of the R class `hyperspec` which may be interesting to add as an entry.

However, I'm not completely sure whether it should be added, as it violates two of the listed criteria:
- maturity: its officially marked as "WIP" with a development version number, therefore by definition not mature. Backwards incompatible changes are possible.
- dependencies reasonable: many of the included functions are simply wrapper functions and thus a lot of external package references, included as "suggests" to not clutter the package install (suggests can be installed at need), exists.

Please feel free to add the package or to decline this PR because of the stated reasons.
I  did not rerender the Rmd as rendering stops due to problems with the github token - in case you decide to add the package I can take a look at the problem (or maybe its faster if you just do it locally).

Thanks,
Konrad

### CODE REVIEW

**Comment by konradmayer** [comment]
I built also another tool which might be of interest.
This is in beta state, but without the source currently available in public (in case I find the time to tidy up and document it its planned in future):

[BIONAMI peak fitting app](https://peakfit.bionami.at/)

**Comment by bryanhanson** [comment]
Hi Konrad, this looks quite interesting.  Give me a few weeks to get caught up on a few other items and we'll get this into the database.  Looks like you are using a recent version of `hyperSpec`  Claudia, myself, Roman Kiselev and Vilmantas Gegzna supervised a student last summer in Google Summer of Code to update a lot of things in `hyperSpec` but there is still more to do and to hopefully get the updated version onto CRAN sometime this year.

**Comment by konradmayer** [comment]
Dear Bryan, no hurry - as I said I'm not even sure whether the package is qualified to be listed due to the stated concerns. I noticed that there is an attempt to split the package into multiple specific sub-packages. In case you can use or built upon certain functions in my package (e.g. my import and export functions for [hySpc.read.txt](https://r-hyperspec.github.io/hySpc.read.txt/)) then feel free to do so (to comply with the main hyperspec package I published it under GPL3, I just saw that the sub-pkgs are MIT - I'm not that deep into licencing, but I assume using my code with a more permissive licence is fine as long as I agree to it). 
Looking forward to the new CRAN version - keep up the good work!

**Comment by bryanhanson** [comment]
@konradmayer I added `hyperSpec.utils` along with some other new entries via 242134eb565a7783c78675bfd6f62616eeebc976 Now working on eliminating some annoying timeout on `GET` requests.  Thanks.

**Pull request closed without merging**
